name: update README
on:
  schedule:
    # Runs every hour
    - cron: '1 * * * *'
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  update-readme-with-DBLP:
    name: Update this repo's README with latest DBLP entries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DBLP"
          feed_list: "https://dblp.org/pers/c/Clemente:Lorenzo.rss"
